version: "3.9"
services:
  keploy-v2:
    container_name: keploy-v2
    image: ghcr.io/keploy/keploy
    privileged: true
    ports:
      - 16789:16789
    environment:
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - /Users/zhumenggang/zhu_work/go/src/docker/tool/keploy/fs/bpf:/sys/fs/bpf
      - /Users/zhumenggang/zhu_work/go/src/docker/tool/keploy/fs/cgroup:/sys/fs/cgroup
      - /Users/zhumenggang/zhu_work/go/src/docker/tool/keploy/kernel/debug:/sys/kernel/debug
      - /Users/zhumenggang/.docker/run/docker.sock:/var/run/docker.sock

    networks:
      - keploy-network
    restart: always
networks:
  app-tier:
    name: keploy-network
    driver: bridge